### ISSUE TITLE
Method "peek" in class StringHandle - Not Yet Implemented

### ISSUE THREAD

**Issue by Util** [parrot/parrot#1011]
Reported by: zefram@fysh.org

The StringHandle PMC class doesn't implement the "peek" method that FileHandle has.  It would be useful, and should be very easy to implement.

-zefram

**Comment by rurban** [comment]
working on seek,peek,tell in branch `rurban/sh-peek-gh1011`

**Comment by rurban** [comment]
done, merging tomorrow

**Comment by rurban** [comment]
Merged into master
