### ISSUE TITLE
Parrot on Darwin/PPC now extremely slow, has test failures

### ISSUE THREAD

**Issue by jkeenan** [parrot/parrot#1162]
In my comment on #1160 yesterday I spoke too soon.  True, as of at least 0d8d1fc, 'make' completes successfully on Darwin/PPC.  However, the resulting parrot experiences test failures and works much more slowly than previously.

Please see the smolder report here: http://smolder.parrot.org/app/projects/report_details/46987.

The failures in t/library/p6object.t are new and reproducible failures.  The test stops running without explanation after:
```
ok 257 - < typeof WXY > eq "WXY"
```
The failures in t/compilers/opsc/08-emitter.t are partially self-induced.  When that test had been running for at least 20 minutes, I inferred that it was hung and used 'kill' to kill it.  The test suite then resumed.  However, the total running time of the test suite was vastly greater than ever before -- more on this below.

Today I ran 'prove -vb t/compilers/opsc/08-emitter.t' and waited long enough for the program to complete.  It took 2191 wallclock seconds -- nearly 37 minutes -- much longer than the entire Parrot test suite took up until earlier this month!

Here are some wallclock running times for Parrot's 'make test' on this machine over the past few months.  I list the date (YYYYMMDD), the commit and the total time.
```
20140803  1f3b66f  1374
20140907  5ac67e4  1331
20141005  4176098  1418
20141122  e25be6d  1797
20141219  0d8d1fc 14181
```
Now, it's been clear for many years that Parrot is never going to be viable in a "production" sense on a machine as old and underpowered as this one.  But the fact that Parrot has been buildable on machines like this for more than 10 years is, IMO, a credit to Parrot.  This machine has often served as the "canary in the coal mine" for Parrot by indicating places where changes in the code base had unintended and initially misunderstood consequences.  (ISTR changes to GC in 2010 led to problems that were subsequently fixed by bacek.)  So I hope that the current problems can be addressed as well.

Thank you very much.
Jim Keenan

**Comment by rurban** [comment]
Back at 966 secs for make test with my darwin/ppc , with -Os, with the release candidate for 7.0.0.
No slowdown observable
