### ISSUE TITLE
Broken win32 builds

### ISSUE THREAD

**Issue by martinstarman** [parrot/parrot#1172]
When I tried to install win32 package from http://sourceforge.net/projects/parrotwin32/ got this message ```The setup files are corrupted. Please obtain a new copy of the program.``` I downloaded two last versions 6.11.0 and 6.8.0 and tried on two different systems WinXP 32b and Win7 64b with the same result.

**Comment by rurban** [comment]
parrot is tested on win32 and win64, with msvc, mingw and cygwin.

The setup files you downloaded are provided by fperrad, you need to report it over there: http://sourceforge.net/projects/parrotwin32/support
We have no idea how he creates them.

I can reproduce your problem: `setup-parrot-6.11.0.exe` is really corrupt.

**Comment by fperrad** [comment]
`setup-parrot-6.11.0.exe` was truncated on SF (6MB instead of 9MB)

now, fixed
