### ISSUE TITLE
miniparrot SEGV on Windows 7 with MSVC

### ISSUE THREAD

**Issue by jnthn** [parrot/parrot#1190]
Trying to build the tagged RELEASE_7_0_1 gives:

    .\miniparrot.exe -Iruntime\parrot\include config_lib.pir > runtime\parrot\include\config.fpmc
    NMAKE : fatal error U1077: '.\miniparrot.exe' : return code '0xc0000005'

Did the usual make realclean, git clean -fdx, and so forth. Nothing unusual otherwise, except perhaps that I configured with `--debugging` to get debug symbols.

**Comment by rurban** [comment]
64bit only.
Justed tested ok with gcc on cygwin64 and mingw64. I'll have to install msvc now. 
So it seems to be a msvc compiler bug.

**Comment by rurban** [comment]
Got msvc 17 now working...

**Comment by rurban** [comment]
The exception happens in `Parrot_NativePCCMethod_invoke`
at 
```
src/pmc/nativepccmethod.pmc:129    PMC *cont = INTERP->current_cont;
```
but both `interp` and `INTERP->current_cont` do look ok to me.

**Comment by rurban** [comment]
It failed in 6.11.0 already, kinda bisecting now.

I needed to patch env for the removed access to the _environ global.

**Comment by rurban** [comment]
891dd90f97a6166a183d88c85cf5362807f00790 broke win64 msvc on all nci calls.
```
-#define D2FPTR(x) UINTVAL2PTR(funcptr_t, PTR2UINTVAL(x))
-#define F2DPTR(x) UINTVAL2PTR(void *, PTR2UINTVAL((funcptr_t) (x)))
+#define D2FPTR(x) UINTVAL2PTR(funcptr_t, PTR2ULONG(x))
+#define F2DPTR(x) UINTVAL2PTR(void *, PTR2ULONG((funcptr_t) (x)))
```
of course, on win64 msvc long is only 4 bytes!!

**Comment by rurban** [comment]
Pushed to master. Not sure yet if we should do a 7.0.2 hotfix for this.

On my win64 msvc system environ access is also broken, which would require `smoke-me/env-gh1191`
@jnthn: Can you please confirm `--gen-parrot=master` works for you on win64/msvc?
