### ISSUE TITLE
7.3.0 fails to build on windows 7 x86_64

### ISSUE THREAD

**Issue by FROGGS** [parrot/parrot#1205]
C:\nqp>perl Configure.pl --backends=parrot --gen-parrot --parrot-option="--icushared=\"C:\icu\lib64\icudt.lib C:\icu\lib64\icuuc.lib\" --icuheaders=C:\icu\include" --pref
ix=C:\nqp\install --make-install
Das System kann den angegebenen Pfad nicht finden.
HEAD is now at 2ec6584... Supported release 7.3.0 - "Peach-faced Lovebird"
[...]
NMAKE : fatal error U1077: '.\miniparrot.exe' : return code '0xc0000135'
Stop.
Command failed (status 512): nmake install-dev

Full log is at https://gist.github.com/FROGGS/98f164584363300736fb

**Comment by rurban** [comment]
We smoke now successfully on 
Environment: MSVC_VERSION=10; Platform: x64
Environment: MSVC_VERSION=10; Platform: x86
Environment: MSVC_VERSION=12; Platform: x64
Environment: MSVC_VERSION=12; Platform: x86
https://ci.appveyor.com/project/rurban/parrot/history
