### ISSUE TITLE
`make clean` and `make realclean` do not clean many generated files.

### ISSUE THREAD

**Issue by Util** [parrot/parrot#1206]
After running `perl Configure.pl; make; make clean; make realclean`, `git clean -dnx` shows many leftover files from the build.

I am certain that most of those files *were* cleaned up by `make clean` or `make realclean` in the past.
I have not yet determined the point when this regressed.

This is a lurking problem in general, but during the 7.6.0 release, it was directly relevant.
The file include/pmc/pmc_default.h was not removed, and so was not rebuilt, and so was not added to MANIFEST.generated, so t/distro/manifest_generated.t failed.
I have added a comment to manifest_generated.t, as a pointer to this bug.

**Comment by jkeenan** [comment]
As of RELEASE_7_0_0, git clean -dnx only showed 3 directories:
```
$ cat f9bb25b.git.clean.dnx.txt 
Would remove lib/Parrot/Config/
Would remove runtime/parrot/languages/JSON/
Would remove runtime/parrot/languages/winxed/
```
Of course, even the fact that 'make realclean' was leaving 3 directories behind is not good.  IIRC -- and we're going back >= 3 years here -- 'make realclean' was expected to be the most thorough clean-up tool (even before we moved to git).

**Comment by jkeenan** [comment]
The section of config/gen/makefiles/root.in which governs the 'realclean' target was touched in commit 396a5b067 on 2014-11-12.  That's probably a good point at which to start investigating.

**Comment by rurban** [comment]
@jkeenan Thanks. Yes, I made prog-clean running archclean in 396a5b0, where I might have forgotten cleaning up some generated files. 
realclean needs to run archclean, but it does so in prog-clean.

The problem with the GEN_CONFIGS and CONFIGURE_GENERATED_FILES in realclean, is that some  generated files do not appear in these lists: see issue #1194 e.g.

**Comment by rurban** [comment]
Found out why. When I optimized RM_F to use the coreutils and not ExtUtils::Command anymore, the string-quoted args with wildchars are not expanded anymore.
`rm "src/pmc/*.dump"` will do nothing.
