### ISSUE TITLE
Parrot + Condor problems?

### ISSUE THREAD

**Issue by tommasoboccali** [parrot/parrot#1209]
Ciao, 
I am trying to set up a uCERNVM image to work with condor.
Often (but not every time), as soon as I start condor, I get

2015/10/07 08:48:51.41 parrot_run[1] <child:163> fatal: cannot execute program with personality 2359296
2015/10/07 08:48:51.41 parrot_run[1] <child:163> notice: received signal 15 (Terminated), killing all my children...
2015/10/07 08:48:51.41 parrot_run[1] <child:163> notice: sending myself 15 (Terminated), goodbye!

the error can be easily via reproduced (when it happens!) via

[root@cmstest ~]# docker run   -e CMS_LOCAL_SITE=T2_IT_Pisa -ti tommasoboccali/cmsui_test /init

(it is just last version of Jakob's docker uCERNVM, I put it on dockerhub for faster accessibility)

and then

bash-4.1# mkdir -p  /var/log/condor
bash-4.1# service condor start
Starting up Condor...    done.
bash-4.1# 2015/10/07 08:54:34.99 parrot_run[1] <child:115> fatal: cannot execute program with personality 2359296
2015/10/07 08:54:34.99 parrot_run[1] <child:115> notice: received signal 15 (Terminated), killing all my children...
2015/10/07 08:54:34.99 parrot_run[1] <child:115> notice: sending myself 15 (Terminated), goodbye!

at first approx, I would like to know what that error means....

thanks a lot!!

tom

**Comment by rurban** [comment]
You are in the wrong software project. 
The Parrot Virtual File System you are using is this one: 
  http://www.cse.nd.edu/~ccl/software/parrot/

Please ask there, in their forum or mailing list

**Comment by tommasoboccali** [comment]
ups, sorry

On Wed, Oct 7, 2015 at 10:59 AM, Reini Urban <notifications@github.com>
wrote:

> You are in the wrong software project.
> The Parrot Virtual File System you are using is this one:
> http://www.cse.nd.edu/~ccl/software/parrot/
>
> Please ask there, in their forum or mailing list
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/parrot/parrot/issues/1209#issuecomment-146122835>.
>



-- 
Tommaso Boccali
INFN Pisa

**Comment by rurban** [comment]
No problem. There's also another parrot, a popular hardware drone.
