### ISSUE TITLE
Who turned off the smokers? travis permissions

### ISSUE THREAD

**Issue by rurban** [parrot/parrot#1237]
https://travis-ci.org/parrot/parrot

"This is not an active repository

You don't have sufficient rights to enable this repo on Travis. 
Please contact the admin to enable it or to receive admin rights yourself."

WTF
----
http://parrot.org/foundation

Board of Directors

* Jerry Gay
* James Keenan
* Jonathan Leto
* Andrew Whitworth

I have no idea who has the admin rights on github. Not visible.

**Comment by coke** [comment]
I clicked "Activate Repository".

**Comment by rurban** [comment]
@coke: Travis works now again.
The appveyor webhook is also gone: https://ci.appveyor.com/project/rurban/parrot/history

**Comment by coke** [comment]
Looks like the webhook is up and green, had a successful delivery at 2017-06-05 16:33:22 (Eastern?)
