### ISSUE TITLE
error: function-like macro 'sizeof' is not defined

### ISSUE THREAD

**Issue by zhou0** [parrot/parrot#1238]
cc -I./include -I./include/pmc -DHAS_FPSETMASK -DHAS_FLOATINGPOINT_H  -pipe -fstack-protector-strong -I/usr/local/include -D_FORTIFY_SOURCE=2 -DHAS_GETTEXT -I/usr/local/lib/libffi-3.2.1/include  -g  -DPIC -fPIC  -fpermissive -funit-at-a-time -Wall -Wextra -Waggregate-return -Wcast-qual -Wdisabled-optimization -Wdiv-by-zero -Wendif-labels -Wno-format -Wimplicit -Wimport -Winit-self -Winline -Winvalid-pch -Werror=missing-braces -Werror=missing-declarations -Wno-missing-format-attribute -Wmissing-include-dirs -Wmultichar -Wpacked -Wpointer-arith -Wreturn-type -Wsequence-point -Wsign-compare -Wstrict-aliasing -Wstrict-aliasing=2 -Wswitch -Wswitch-default -Werror=undef -Wno-unused -Wvariadic-macros -Wwrite-strings -Wc++-compat -Werror=declaration-after-statement -Werror=implicit-function-declaration -Werror=missing-prototypes -Werror=nested-externs -Werror=old-style-definition -Werror=strict-prototypes -fvisibility=hidden -Isrc/atomic/. -Isrc -o src/atomic/gcc_x86.o -c src/atomic/gcc_x86.c
```
src/atomic/gcc_x86.c:54:46: error: function-like macro 'sizeof' is not defined
#if defined(PARROT_HAS_AMD64_GCC_CMPXCHG) || __WORDSIZE == 64
                                             ^
./include/parrot/compiler.h:12:23: note: expanded from macro '__WORDSIZE'
#  define __WORDSIZE (sizeof(void*) * 8)
                      ^
src/atomic/gcc_x86.c:88:46: error: function-like macro 'sizeof' is not defined
#if defined(PARROT_HAS_AMD64_GCC_CMPXCHG) || __WORDSIZE == 64
                                             ^
./include/parrot/compiler.h:12:23: note: expanded from macro '__WORDSIZE'
#  define __WORDSIZE (sizeof(void*) * 8)
                      ^
2 errors generated.
gmake: *** [Makefile:613: src/atomic/gcc_x86.o] Error 1
```

**Comment by rurban** [comment]
Which compiler is that? 
**sizeof** is a C89 keyword: http://www.open-std.org/JTC1/SC22/wg14/www/docs/n1124.pdf

the parens look do superfluous here, but that's our coding standard.

**Comment by zhou0** [comment]
cc --version
FreeBSD clang version 4.0.0 (tags/RELEASE_400/final 297347) (based on LLVM 4.0.0)
Target: x86_64-unknown-freebsd12.0
Thread model: posix
InstalledDir: /usr/bin

The error remains after applying the patch. 

src/atomic/gcc_x86.c:54:46: error: function-like macro 'sizeof' is not defined
#if defined(PARROT_HAS_AMD64_GCC_CMPXCHG) || __WORDSIZE == 64
                                             ^
./include/parrot/compiler.h:12:27: note: expanded from macro '__WORDSIZE'
#  define __WORDSIZE (8 * sizeof(void*))
                          ^
src/atomic/gcc_x86.c:88:46: error: function-like macro 'sizeof' is not defined
#if defined(PARROT_HAS_AMD64_GCC_CMPXCHG) || __WORDSIZE == 64
                                             ^
./include/parrot/compiler.h:12:27: note: expanded from macro '__WORDSIZE'
#  define __WORDSIZE (8 * sizeof(void*))
                          ^
2 errors generated.
*** Error code 1

Stop.
make: stopped in /usr/home/lzhou/github.com/parrot/parrot/archive/parrot-RELEASE_8_1_0

**Comment by zhou0** [comment]
it seems that sizeof is not recognized by the preprocessor inside #if according to this https://en.wikibooks.org/wiki/C_Programming/Preprocessor

**Comment by rurban** [comment]
Interesting. I found that this should fix it:
```
#ifndef __WORDSIZE
#  ifdef __SIZE_WIDTH__
#    define __WORDSIZE __SIZE_WIDTH__
#  else
#    define __WORDSIZE (8 * sizeof void*)
#  endif
#endif
```

**Comment by vendethiel** [comment]
Sounds surprising. Supposedly `sizeof` requires parentheses for types.

**Comment by zhou0** [comment]
it is fixed. thanks.

**Comment by rurban** [comment]
I saw several clang bug reports for sizeof. Types should use parens, yes, but apparently their cpp struggles with it. We might want to reconsider this.
