### ISSUE TITLE
useless entries in /etc/resolv.conf

### ISSUE THREAD

**Issue by Whichcraft** [parrot/parrot#1240]
grep nameserver /etc/resolv.conf
nameserver 92.222.97.145
nameserver 192.99.85.244
nameserver 208.67.222.222
nameserver 208.67.220.220
nameserver 92.222.97.145
nameserver 192.99.85.244
nameserver 185.121.177.177

from man 5 resolv.conf:

       nameserver Name server IP address
              Internet address of a  name  server  that  the  resolver  should
              query,  either  an  IPv4  address  (in dot notation), or an IPv6
              address in colon (and possibly dot) notation as  per  RFC  2373.
              Up  to  MAXNS  (currently 3, see <resolv.h>)

so only the first 3 will ever come into play. The rest is usless, even when

# Round Robin
options rotate

is set.

 #cat resolv.py 
import socket
for x in range(10):
   print socket.getaddrinfo('redhat.com', 80);

strace -e trace=connect python resolv.py 2>&1 | grep 53
connect(3, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("92.222.97.145")}, 16) = 0
connect(3, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("192.99.85.244")}, 16) = 0
connect(3, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("208.67.222.222")}, 16) = 0
connect(3, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("92.222.97.145")}, 16) = 0
connect(3, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("192.99.85.244")}, 16) = 0
connect(3, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("208.67.222.222")}, 16) = 0
connect(3, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("92.222.97.145")}, 16) = 0
connect(3, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("192.99.85.244")}, 16) = 0
connect(3, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("208.67.222.222")}, 16) = 0
connect(3, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("92.222.97.145")}, 16) = 0

Best regards

Whichcraft

**Comment by jkeenan** [comment]
This does not appear to relate to any code in the Parrot repository.

**Comment by Whichcraft** [comment]
The seem to be pulled in by resolvconf (?) somehow. I surely never have set this DNS servers manually, nor by DHCP.

**Comment by vendethiel** [comment]
@Whichcraft you're talking about https://github.com/ParrotSec... You didn't even read the repository description...

**Comment by Whichcraft** [comment]
indeed. my bad. sorry.
