### ISSUE TITLE
Change exit node ui error

### ISSUE THREAD

**Issue by Bry-fi** [parrot/parrot#1241]
When I attempt to change my exit node, the menu will say "select a country" then disappears a second later disallowing me from selecting a country. This occurs in 4.14.0 and the recent one.

**Comment by svatsan** [comment]
This is [ParrotVM](http://parrot.org) and does not have anything to do with
this issue. Perhaps, you're thinking of [ParrotSec](
https://github.com/parrotSec)? Their website is here:
https://www.parrotsec.org/
