### ISSUE TITLE
A 'tools/docs/mk_pod2man.pl' script to autogen the installable binaries' POD files into *roff pages ...

### ISSUE THREAD

**Issue by ayardley** [parrot/parrot#228]
and install the same.

The script needs to do, roughly, the following:

1. check config to ensure we have a validate value entry for the 'mandir' key;

if no, do nothing;
else

2. gather up a list of the *.pod files in 'docs/binaries';
3. create a 'docs/man1' directory;
4. run each POD file through pod2man and redirect the *roff output to 'docs/man1';[*]
5. output a makefile into the 'docs/man1' directory;
6. update the main Makefile to copy the *roff files to the directory pointed to by $PConfig{mandir};

----------
[*] Perhaps compress the *roff files.  (I do not know whether most platforms with man pages want compressed files or not.)

**Comment by rurban** [comment]
We already generate manpages from pod since 2012
