### ISSUE TITLE
pcre_compile picked wrong function signature letter.

### ISSUE THREAD

**Issue by ronaldxs** [parrot/parrot#258]
The pcre_compile library function takes a const char ** parameter which SHOULD have been matched by a capital 'V' in the signature but a somewhat similar capital 'B' was picked instead resulting in the error string not being passed back properly.

The patches have been tested on windows and ubuntu.  Note that the changes to src/nci/extra_thunks.c are generated by tools/dev/mk_nci_thunks.pl but are included here as the .c file is under version control and I don't think it's genned by the Makefile.

See also the irc discussion here: [http://irclog.perlgeek.de/parrot/2010-09-18#i_2840413]

Originally http://trac.parrot.org/parrot/ticket/1795

**Comment by rurban** [comment]
Obsolete patches since the nci rewrite, which does not take strings of chars anymore.
But we take the improved test.
