### ISSUE TITLE
perl Configure.pl finds icu but doesn't set it up

### ISSUE THREAD

**Issue by parrot** [parrot/parrot#307]
perl Configure.pl finds icu during config but doesn't set you up to use it.

perl Configure.pl says:
...
auto::icu -          Is ICU installed....................................yes.

But during make, the following error is reported:
Invoking Parrot to generate runtime/parrot/include/config.fpmc --cross your fingers
./miniparrot config_lib.pasm > runtime/parrot/include/config.fpmc
./miniparrot: error while loading shared libraries: libicuuc.so.42: cannot open shared object file: No such file or directory
gmake: *** [runtime/parrot/include/config.fpmc] Error 127

Originally http://trac.parrot.org/parrot/ticket/1309 by getpsimon

**Comment by rurban** [comment]
We improved the icu probes and set the proper status if failed in 2015.
Additionally you can use the `--icushared=` and `--icuheaders=` flags
