### ISSUE TITLE
win32 Wide API needed . 'make smoke' failed 63 tests.

### ISSUE THREAD

**Issue by zhuomingliang** [parrot/parrot#380]
It failed 63 tests.

see http://smolder.plusthree.com/app/public_projects/report_details/17984

parrot fails to load:
.\parrot.exe -o C:/DOCUME~1/ÃÂÃÂ¢ÃÂ»ÃÂ¨ÃÂÃÂÃÂÃÂ/LOCALS~1/Temp/tySepN24eO

The Windows Wide API is not enabled.

As workaround $TEMP could be checked to point to a pure ascii path.

Originally http://trac.parrot.org/parrot/ticket/326

**Comment by rurban** [comment]
All external strings (paths args) are now platform encoded.
