### ISSUE TITLE
RFC: Remove or fix SDL

### ISSUE THREAD

**Issue by coke** [parrot/parrot#436]
`t/examples/catchall.t` shows a lot of failures even trying to /compile/ the SDL examples/libraries, let alone run them.

I propose we remove the library and examples before the next supported release - it can go back into a release once it builds again.

Or someone could fix it.

Originally: http://trac.parrot.org/parrot/ticket/411

**Comment by rurban** [comment]
I removed the wrong `examples/nci/sdl_blue_rectangle.pir`

we have a modern nci version in `examples/sdl/blue_rect.pir` instead. 
which now with even works in `rurban/t-nci-sig`
