### ISSUE TITLE
compacting/copying gc

### ISSUE THREAD

**Issue by allisonrandal** [parrot/parrot#632]
Implement a compacting/copying garbage collection module for Parrot. This will require some changes to the Parrot core to make it possible to move objects.

Originally http://trac.parrot.org/parrot/ticket/616

**Comment by rurban** [comment]
Just a note: Our generational collector gms is far from being good. It is in fact horrible, 20% slower than ms2 without generations. 
A copying collector would be at least twice as fast as ms2, but would need at least twice as much memory.
