### ISSUE TITLE
update copyright notices in various frequently updated files

### ISSUE THREAD

**Issue by ayardley** [parrot/parrot#719]
For example, *.html docs and to quote dukeleto, "certain files, which *do* get updated all the time, should have the latest copyright notices. For instance, when I run "parrot --version", it still tells me it is copyright 2001-2011, which is outdated."

Also, to quote Jim Keenan, "check t/codingstd/copyright.t ... for recency of copyright date, i.e., whether the copyright for a file that was created before 2012 and modified in 2012 has been updated to: *-2012."

**Comment by rurban** [comment]
2015-01-11:
```
$ TEST_SLOW=1 time perl5.21.8-nt@blead -S prove t/codingstd/copyright.t
t/codingstd/copyright.t .. # Running very slow copyright year checks: >10 minutes
t/codingstd/copyright.t .. ok   
All tests successful.
Files=1, Tests=4, 1366 wallclock secs ( 0.02 usr  0.00 sys + 1310.48 cusr 35.72 csys = 1346.22 CPU)
Result: PASS
1310.56 user 35.72 system 22:45.59 elapsed 98%CPU (0 avgtext+0 avgdata 89328 maxresident)k
```
