### ISSUE TITLE
Expose icu's FoldCase operation to user space

### ISSUE THREAD

**Issue by moritz** [parrot/parrot#786]
Rakudo needs the FoldCase operation (see http://icu-project.org/apiref/icu4c/ustring_8h.html#ab6709b5a5c1606cf0d3ea24934d9acce ) to implement the fc() built-in subroutine. Exposing the FoldCase function from ICU as an op (preferred) or a method in the String PMC would help Rakudo here.

**Comment by rurban** [comment]
rebased to the branch `smoke-me/foldcase_str` and added some testcases

**Comment by rurban** [comment]
Will be in 8.2.0, PBC_COMPAT bumped to 13.1
