### ISSUE TITLE
Recursion limit is a bad default

### ISSUE THREAD

**Issue by Util** [parrot/parrot#991]
Reported by: zefram@fysh.org

By default, Parrot imposes an arbitrary limit on recursion, of 1000 nested calls. The limit is changeable: it can be set via the "recursion_limit" method on the interpreter object obtained from getinterp, and setting it to -1 effectively removes the limit entirely. I think having a reachable limit by default is a bad idea. The limit means that whether code works depends not just on its intrinsic characteristics but also on the nesting depth from which it is called.

For example:
```
$ cat t27.pir
.sub foo
        .param int i
        if i == 0 goto done
        $I0 = i - 1
        $S0 = foo($I0)
        .return($S0)
        done:
        .return("ok")
.end
.sub bar
        .tailcall foo(997)
.end
.sub baz
        $S0 = bar()
        say $S0
.end
.sub main :main
        $S0 = bar()
        say $S0
        baz()
.end
$ ./parrot t27.pir
ok
maximum recursion depth exceeded
current instr.: 'foo' pc 0 (t27.pir:1)
called from Sub 'foo' pc 19 (t27.pir:5)
... call repeated 996 times
called from Sub 'baz' pc 45 (t27.pir:14)
called from Sub 'main' pc 72 (t27.pir:20)
```

(Never mind that foo could use tailcalling or just return "ok" immediately: it's standing in for any complex code that would actually require recursion.) The first time bar() is called, from main, it succeeds. The second time, when it's called from baz, it fails. The two calls to bar() look identical. One would expect that, if the call from main works, then it would still work if it's placed in a subroutine (baz) that is called from main. This is a very basic kind of transformation of a program, that we rely on all the time, and the recursion limit means that it doesn't work in the general case.

If you expect Parrot code to normally run with this limit in place, then a lot of documentation needs to change to reflect it. For example, the invokecc op is documented as:

> Call the subroutine in $1 and generate a new return continuation,
> if needed.

with the recursion limit, it should be documented as:

> If the current call context is nested less than 999 levels from
> the top level then call the subroutine in $1, generating a new
> return continuation if needed.	Otherwise generate an exception.

But, worse, every subroutine that runs on Parrot needs documentation of the form:

> =item munge_frobnitz()
> 
> If called from a context that is nested less than 987 levels from
> the top level then munge the frobnitz, returning the number of
> flanges that were frobbed.  Otherwise generate an exception.

and an internal implementation detail (the number of call nesting levels used internally) leaks out all over the place. This is a maintenance nightmare.

If you're *not* expecting Parrot code to normally run with this limit in place, but the default is to have the limit, then every top-level program is effectively expected to contain the boilerplate to switch the limit off. It's only two lines of boilerplate, not an appalling imposition on the programmers who are paying attention. But inevitably the vast majority of programs won't get the boilerplate inserted, and will thus break functions that relied on the top level doing this job.

Someone's going to say "but it's just like the fact that you can unpredictably run out of memory". It's not like that: this is a small and arbitrary limit that affects programs that are in no danger of exhausting memory. Adding more memory to the system doesn't change the recursion limit.

Nor is the limit a systematic attempt to catch runaway programs before they exhaust memory. You're free to consume as much memory as you like as long as you do it iteratively, or via tailcalling, or if you disguise your recursion as tailcalling by using explicit continuation passing. The recursion limit seems to be just... training wheels, to prevent n00bs getting themselves confused by this newfangled recursion trickery.

As having a recursion limit breaks ordinary function composition semantics, I think the training wheels shouldn't be in place by default. I have no objection to the training wheels being a non-default option. It's being semantically broken *by default* that's the problem.

-zefram

```
Summary of my parrot 5.5.0 configuration:
  configdate='Sun Sep 22 18:01:32 2013 GMT'
  Platform:
    osname=linux, archname=x86_64-linux-gnu-thread-multi
```

**Comment by rurban** [comment]
Almost every fast language implementation uses such a recursion limit around 1000. It's not entirely unexpected.

However with the documented parrot CPS system it is unexpected. The problem was the "pdd calling convention refactor" with 2.3.0 which broke CPS and the calling convention and performance completely.

e.g. https://github.com/parrot/parrot-bench#comments
RELEASE_2_3_0: -11.86% new pcc calling convention
